application: tfg-server
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: tfg_server.app


libraries:
- name: jinja2
  version: "2.6"
- name: ssl
  version: latest
- name: numpy
  version: "1.6.1"
